apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    env: demo

# In kind cluster, we can find the app on localhost:nodePort by exposing the ports using extraPortMappings
# otherwise, we can find the app on nodeIP:nodePort
